[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["corepack enable && corepack prepare pnpm@latest --activate"]

[phases.install]
cmds = ["cd financial-dashboard && pnpm install"]

[phases.build]
cmds = ["cd financial-dashboard && pnpm build"]

[start]
cmd = "npx serve financial-dashboard/dist -s -l 3000"
